### ISSUE TITLE
vscode安装扩展完之后，扩展启动报错

### ISSUE THREAD

**Issue by xuxygo** [jiaolong1021/vue-helper#76]
vscode版本1.89.1
vue-helper版本 2.5.1
报错日志如下：

2024-05-11 15:23:39.490 [error] Activating extension shenjiaolong.vue-helper failed due to an error:
2024-05-11 15:23:39.490 [error] Error: ENOENT: no such file or directory, scandir
    at Object.readdirSync (node:fs:1529:3)
    at Object.t.readdirSync (node:electron/js2c/node_init:2:11289)
    at li.search (c:\Users\username\.vscode\extensions\shenjiaolong.vue-helper-2.5.1\dist\client.js:2:998)
    at new di (c:\Users\username\.vscode\extensions\shenjiaolong.vue-helper-2.5.1\dist\client.js:2:3049)
    at Fn (c:\Users\username\.vscode\extensions\shenjiaolong.vue-helper-2.5.1\dist\client.js:5009:5356)
    at kn (c:\Users\username\.vscode\extensions\shenjiaolong.vue-helper-2.5.1\dist\client.js:5009:5309)
    at Function.kb (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:13465)
    at Function.jb (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:13175)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:159:11197
    at h.n (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6281)
    at h.m (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6244)
    at h.l (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:5701)
2024-05-11 15:23:41.868 [error] [w88975.code-translate] provider FAILED
2024-05-11 15:23:41.869 [error] TypeError: Cannot read properties of undefined (reading 'document')
    at Object.provideHover (c:\Users\username\.vscode\extensions\w88975.code-translate-1.0.20\src\index.js:30:55)
    at k.provideHover (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:93838)
    at d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:122706
    at Ae.s (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:120151)
    at Ae.$provideHover (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:122693)
    at c.S (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5505)
    at c.Q (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:5271)
    at c.M (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:4323)
    at c.L (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:3440)
    at a.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:2227)
    at o.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
    at o.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
    at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
    at a.value (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:8023)
    at o.y (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:660)
    at o.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:82:877)
    at u.fire (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:107:14175)
    at MessagePortMain.<anonymous> (d:\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:176:6303)
    at MessagePortMain.emit (node:events:517:28)
    at MessagePortMain.emit (node:domain:489:12)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)

**Comment by jiaolong1021** [comment]
能截个vscode报错图吗？

**Comment by jiaolong1021** [comment]
该问题将在下一个版本解决

**Comment by xuxygo** [comment]
> 能截个vscode报错图吗？

![image](https://github.com/jiaolong1021/vue-helper/assets/17491408/cc97b855-ad12-426f-9db3-b2a938bb4a77)
